[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[api]
  debug = true
  dashboard = true

[log]
  format = "json"

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"

[providers.docker]
  endpoint = "tcp://docker-api-proxy:2375"
  swarmMode = true
  exposedByDefault = false

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

  [entryPoints.dashboard]
    address = ":8080"

  [entryPoints.metrics]
    address = ":8082"

[certificatesResolvers.le.acme]
email = "guillaume.maka@gmail.com"
storage = "/letsencrypt/acme.json"
  [certificatesResolvers.le.acme.dnsChallenge]
    provider = "route53"
  # [certificatesResolvers.traefik.acme.dnsChallenge]
  #   provider = "digitalocean"
  #   delayBeforeCheck = 0
