version: "3.7"

x-default-opts: &default-opts
  logging:
    options:
      max-size: "10m"
  deploy:
    placement:
      constraints:
        - node.role == manager
    replicas: 1
    restart_policy:
      condition: on-failure

services:
  docker-api-proxy:
    <<: *default-opts
    image: tecnativa/docker-socket-proxy
    networks:
      - internal
    privileged: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - 2375
  proxy:
    <<: *default-opts
    image: traefik:2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8082"
    networks:
      - web
      - internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`traefik.domain.com`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.usersFile=/etc/traefik/users"
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
    secrets:
      - source: traefik-users
        target: /etc/traefik/users
        mode: 0600
  prometheus:
    <<: *default-opts
    image: prom/prometheus
    command:
      - --config.file=/prometheus-data/prometheus-config.yml
    networks:
      - internal
    configs:
      - source: prometheus-config.yml
        target: /prometheus-data/prometheus-config.yml
  grafana:
    <<: *default-opts
    image: grafana/grafana:5.2
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
    networks:
      - internal
    # configs:
    #   - source: grafana.ini
    #     target: /etc/grafana/grafana.ini
    secrets:
      - grafana_admin_password

networks:
  web:
    external: true

configs:
  grafana.ini:
    file: ./grafana.ini
  prometheus-config.yml:
    file: ./prometheus-config.yml
  traefik.toml:
    file: ./traefik.toml

secrets:
  grafana_admin_password:
    external: true
  traefik-users:
    file: ./users
