defaultEntryPoints = ["http", "https"]

[api]
entrypoint = "dashboard"
dashboard = true

[docker]
swarmMode = true
exposedByDefault = false

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.dashboard]
  address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
      usersFile = "/etc/traefik/users"


[acme]
email = "admin@guillaumemaka.com"
entryPoint = "https"
onHostRule = true
storage = "acme.json"
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
[[acme.domains]]
  main = "*.guillaumemaka.com"