global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  dashboard:
    address: :8080
  http:
    address: :80
  https:
    address: :443
providers:
  providersThrottleDuration: 2s
  docker:
    endpoint: tcp://docker-api-proxy
    swarmMode: true
    swarmModeRefreshSeconds: 15s
api:
  insecure: true
  dashboard: true
log: {}
certificatesResolvers:
  default:
    acme:
      email: admin@guillaumemaka.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
